#!/bin/bash

# Define common video file extensions
video_extensions="mp4|avi|mkv|mov|flv|wmv|webm|m4v|mpg|mpeg|3gp|ogv|rm|rmvb|asf|qt|divx|dv|m2ts|mts|ts|vob|f4v|mxf"

# Define the path to the watched videos file in the .config folder
watched_videos_file="$HOME/.config/watched_videos.txt"

# Function to open the selected video file with mpv
open_video() {
    mpv "$1" > /dev/null 2>&1 &
}

# Function to mark a video as watched
mark_watched() {
    echo "$1" >> "$watched_videos_file"
}

# Function to check if a video has been watched
is_watched() {
    grep -Fxq "$1" "$watched_videos_file"
}

# Loop to keep fzf window open for selecting videos
last_selected_item=""
while true; do
    # Use fzf to select a video file with a visual indicator for watched videos
    video_file=$(find . -type f -regextype posix-extended -iregex ".*\.(${video_extensions})" | while read -r file; do
        if is_watched "$file"; then
            echo "● $file"
        else
            echo "○ $file"
        fi
    done | fzf --ansi --preview 'mediainfo {}' --preview-window=right:60%:wrap --marker=">" --pointer=">" --print-query --query="$last_selected_item" | sed 's/^[●○] //')

    # Check if a video file was selected
    if [[ -n "$video_file" ]]; then
        open_video "$video_file"
        mark_watched "$video_file"
        last_selected_item="$video_file"
    else
        # Exit the loop if no video file was selected (e.g., user pressed Esc)
        break
    fi
done
